version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: mydatabase
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"
    networks:
      - my-network
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  spring-app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - my-network

networks:
  my-network:
